apiVersion: v1
kind: Service
metadata:
  name: infinispan-discovery-service
  labels:
    app: infinispan
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: infinispan
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
